{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crowapp.serviceAccountName" . }}
  labels:
{{ include "crowapp.labels" . | nindent 4 }}
{{- end -}}
